name: kurl

on:
  push:
   branches:
     - unstable
     - master
     - main
   paths:
     - 'kurl-installer.yaml'

jobs:
  create-kubernetes-installer:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create a new kubernetes installer
      run: make kurl
      env:
        REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
        REPLICATED_APP: ${{ secrets.REPLICATED_APP }}



